### ISSUE TITLE
can't get "alphanumeric" or "strong" tabs to show a "0" or "1"(!?)

### ISSUE THREAD

**Issue by ghscuuo** [passhelp/passhelp#8]
https://passhelp.github.io/generator
I was just playing around, trying to use the tool to generate a small handful of random numbers (to use to choose character positions to tweak in the "phrase" output). 

So, instead of going to random.org to get a few random numbers, I figured I could just pull the random numbers from the "alphanumeric" tab.  Clicking the "alphanumeric" tab many, many times (100 or more?), I could not get a "0" or "1" to be presented in any of the displayed random strings.  Same for the "strong" tab.   When I clicked the "strongest" tab, I immediately started to see 0's and 1's.  

I can't believe I'm typing this. I must be wrong. Anybody else seeing this?

**Comment by jpeddicord** [comment]
Heya! You are correct; the website uses the "friendly" version (`alphanumeric_friendly`) of this generator which excludes look-alike characters that may be mistaken visually:

https://github.com/passhelp/passhelp/blob/75d0dd3b8181c6e323162df1dfee703f6c445780/src/generators/character.ts#L40-L47

The library itself provides the option, but I made the specific choice to omit these few characters for usability on the website. If you want the strongest possible random combination, you'd want to look towards the "strongest" option on the side.

**Comment by jpeddicord** [comment]
Alternatively, if you want to change this for your own use, save a copy of the page https://passhelp.github.io/generator and replace `data-alphabet="alphanumeric_friendly"` with `data-alphabet="alphanumeric"`. That should do it!

**Comment by ghscuuo** [comment]
OMG!  Thanks for the detailed explanation and workaround!

**Comment by ghscuuo** [comment]
Ah, now I see (and understand): "look-alikes excluded"
