### ISSUE TITLE
can one use api in browser address bar?

### ISSUE THREAD

**Issue by ghscuuo** [passhelp/passhelp#9]
I want to play around with this:
// include uppercase, special, and digit characters
passhelp.phrase(3, true); // "Stylish:question8splinter"

I can pass this in the browser address bar:
https://passhelp.github.io/generator/#phrase:3

How can I pass the "true" in the browser address bar?  I tried a few guesses, but failed. 

Thanks in advance. 

(While we're at it, might as well ask about how to do this in the address bar as well:
// 8 character alphanumeric for those silly banks. ensure that
// it has 1 digit, 1 upper-case and 1 lower-case character
passhelp.character(8, passhelp.alphabets.alphanumeric, true); // "A2nJEH4o")

**Comment by jpeddicord** [comment]
(Sorry for the slow reply!) The web version does not offer a full API, it's more or less only built to be able to bookmark what you can see and click visually. But if you're curious / want to tinker, there's options here: https://github.com/passhelp/passhelp/blob/master/web/src/state.ts.

E.g. if you wanted to include that `true` option, you'd want to add a preset (as a button, even), use that preset in the URL, and then change a portion of the app to pass that along to the library.
